import { TrackingMode, UserSettings } from './types';

export const TRANSLATIONS = {
  fr: {
    appName: 'SafeCycle',
    tabs: {
      home: 'Accueil',
      journal: 'Suivi',
      stats: 'Stats',
      settings: 'Réglages',
    },
    flow: {
      none: 'Aucun',
      spotting: 'Spotting',
      light: 'Léger',
      medium: 'Moyen',
      heavy: 'Abondant',
    },
    symptoms: {
      common: ['Crampes', 'Fatigue', 'Maux de tête', 'Sensibilité poitrine', 'Gonflement', 'Acné', 'Changement d\'humeur', 'Insomnie'],
      sopk: ['Pilosité accrue', 'Perte de cheveux', 'Difficulté poids'],
      endometriosis: ['Douleur pelvienne', 'Douleur lombaire', 'Douleur intercourse', 'Nausées'],
      contraception: ['Prise oubliée', 'Effets secondaires', 'Spotting'],
    },
    modes: {
      simple: 'Simple',
      sopk: 'SOPK',
      endometriosis: 'Endométriose',
      contraception: 'Contraception',
    },
    phases: {
      menstrual: 'Menstruation',
      follicular: 'Phase folliculaire',
      ovulation: 'Ovulation',
      luteal: 'Phase lutéale',
    },
    stats: {
      avgCycle: 'Cycle moyen',
      avgLuteal: 'Phase lutéale',
      days: 'jours',
      noData: 'Ajoutez 3 cycles pour voir vos tendances',
      noDataHint: 'Ajoutez vos premiers cycles pour voir vos statistiques',
      subtitle: 'Vos tendances sur les 6 derniers mois',
      cycleLength: 'Longueur des cycles',
      symptomsByPhase: 'Symptômes par phase',
      predictions: 'Prochaines prévisions',
      nextPeriod: 'Prochaines règles',
      estimatedOvulation: 'Ovulation estimée',
      confidence: 'Confiance',
      last: 'dernier',
    },
    actions: {
      save: 'Enregistrer',
      cancel: 'Annuler',
      delete: 'Supprimer',
      add: 'Ajouter',
      edit: 'Modifier',
      today: 'Aujourd\'hui',
      upgradePro: 'Passer à Lifetime',
      exportData: 'Exporter mes données',
      deleteAll: 'Supprimer toutes les données',
    },
    empty: {
      noEntries: 'Aucun suivi enregistré',
      startTracking: 'Commencez votre premier suivi',
      noEntriesForDate: 'Aucun suivi pour cette date',
    },
    privacy: {
      badge: 'Zero-Knowledge',
      description: 'Vos données sont chiffrées et stockées uniquement sur cet appareil.',
    },
    confirm: {
      deleteEntry: 'Supprimer cette entrée ?',
      deleteAll: 'Cette action est irréversible. Toutes vos données seront supprimées définitivement.',
    },
    entries: 'entrées',
    entry: 'entrée',
    purchase: {
      title: 'SafeCycle Lifetime',
      price: '19,99 $',
      features: ['Accès à vie', 'Toutes les fonctionnalités', 'Aucune publicité', 'Support prioritaire'],
      cta: 'Acheter maintenant',
    },
    settings: {
      trackingMode: 'Mode de suivi',
      notifications: 'Notifications',
      reminders: 'Rappels de suivi',
      predictions: 'Prédictions',
      medication: 'Rappels médicament',
      language: 'Langue',
      dangerZone: 'Zone dangereuse',
      exportJson: 'Exporter mes données (JSON)',
      encryptedWith: 'Données chiffrées avec AES-256-GCM',
    },
    toast: {
      entryAdded: 'Entrée ajoutée',
      entryUpdated: 'Entrée mise à jour',
      entryDeleted: 'Entrée supprimée',
      saveError: 'Erreur lors de la sauvegarde',
      dataExported: 'Données exportées',
      exportError: 'Erreur lors de l\'export',
      dataDeleted: 'Toutes les données ont été supprimées',
      deleteError: 'Erreur lors de la suppression',
      purchaseNotImplemented: 'Paiement non implémenté dans cette démo',
    },
  },
  en: {
    appName: 'SafeCycle',
    tabs: {
      home: 'Home',
      journal: 'Journal',
      stats: 'Stats',
      settings: 'Settings',
    },
    flow: {
      none: 'None',
      spotting: 'Spotting',
      light: 'Light',
      medium: 'Medium',
      heavy: 'Heavy',
    },
    symptoms: {
      common: ['Cramps', 'Fatigue', 'Headache', 'Breast tenderness', 'Bloating', 'Acne', 'Mood changes', 'Insomnia'],
      sopk: ['Increased hair growth', 'Hair loss', 'Weight difficulty'],
      endometriosis: ['Pelvic pain', 'Back pain', 'Pain during intercourse', 'Nausea'],
      contraception: ['Missed pill', 'Side effects', 'Spotting'],
    },
    modes: {
      simple: 'Simple',
      sopk: 'PCOS',
      endometriosis: 'Endometriosis',
      contraception: 'Contraception',
    },
    phases: {
      menstrual: 'Menstruation',
      follicular: 'Follicular phase',
      ovulation: 'Ovulation',
      luteal: 'Luteal phase',
    },
    stats: {
      avgCycle: 'Average cycle',
      avgLuteal: 'Luteal phase',
      days: 'days',
      noData: 'Add 3 cycles to see your trends',
      noDataHint: 'Add your first cycles to see your statistics',
      subtitle: 'Your trends over the last 6 months',
      cycleLength: 'Cycle length',
      symptomsByPhase: 'Symptoms by phase',
      predictions: 'Upcoming predictions',
      nextPeriod: 'Next period',
      estimatedOvulation: 'Estimated ovulation',
      confidence: 'Confidence',
      last: 'last',
    },
    actions: {
      save: 'Save',
      cancel: 'Cancel',
      delete: 'Delete',
      add: 'Add',
      edit: 'Edit',
      today: 'Today',
      upgradePro: 'Go Lifetime',
      exportData: 'Export my data',
      deleteAll: 'Delete all data',
    },
    empty: {
      noEntries: 'No entries recorded',
      startTracking: 'Start your first tracking',
      noEntriesForDate: 'No tracking for this date',
    },
    privacy: {
      badge: 'Zero-Knowledge',
      description: 'Your data is encrypted and stored only on this device.',
    },
    confirm: {
      deleteEntry: 'Delete this entry?',
      deleteAll: 'This action is irreversible. All your data will be permanently deleted.',
    },
    entries: 'entries',
    entry: 'entry',
    purchase: {
      title: 'SafeCycle Lifetime',
      price: '$19.99',
      features: ['Lifetime access', 'All features', 'No ads', 'Priority support'],
      cta: 'Buy now',
    },
    settings: {
      trackingMode: 'Tracking mode',
      notifications: 'Notifications',
      reminders: 'Tracking reminders',
      predictions: 'Predictions',
      medication: 'Medication reminders',
      language: 'Language',
      dangerZone: 'Danger zone',
      exportJson: 'Export my data (JSON)',
      encryptedWith: 'Data encrypted with AES-256-GCM',
    },
    toast: {
      entryAdded: 'Entry added',
      entryUpdated: 'Entry updated',
      entryDeleted: 'Entry deleted',
      saveError: 'Error saving',
      dataExported: 'Data exported',
      exportError: 'Error exporting data',
      dataDeleted: 'All data has been deleted',
      deleteError: 'Error deleting data',
      purchaseNotImplemented: 'Payment not implemented in this demo',
    },
  },
};

export type Language = 'fr' | 'en';

export const DEFAULT_SETTINGS: UserSettings = {
  mode: 'simple',
  notifications: {
    reminders: true,
    predictions: true,
    medication: false,
  },
  language: 'fr' as Language,
  hasPro: false,
};

export const DB_NAME = 'safecycle-db';
export const DB_VERSION = 1;

export const FLOW_COLORS: Record<string, string> = {
  none: 'transparent',
  spotting: '#E8D5C4',
  light: '#D4A574',
  medium: '#C17B7B',
  heavy: '#8B4D4D',
};
