export const recipePlanTranslations = {
  en: {
    title: "28-Day Estrogen Recipe Plan",
    desc: "A daily guide to nourishing your body according to estrogen fluctuations throughout your cycle.",
    btn: "View 28-Day Plan",
    phases: {
      menstrual: "Menstrual Phase (Days 1-5): Low Estrogen",
      follicular: "Follicular Phase (Days 6-13): Rising Estrogen",
      ovulatory: "Ovulatory Phase (Days 14-16): Peak Estrogen",
      luteal: "Luteal Phase (Days 17-28): Estrogen Drops & Fluctuates"
    },
    days: [
      { day: 1, title: "Comforting Lentil & Spinach Soup", desc: "Rich in iron to replenish blood loss." },
      { day: 2, title: "Warm Chia & Berry Porridge", desc: "Anti-inflammatory omega-3s for cramps." },
      { day: 3, title: "Mushroom Veggie Broth", desc: "Hydrating and packed with trace minerals." },
      { day: 4, title: "Mild Chickpea Coconut Curry", desc: "Magnesium for muscle relaxation." },
      { day: 5, title: "Cacao, Banana & Almond Smoothie", desc: "Gentle energy and mood support." },
      { day: 6, title: "Crunchy Kale & Pomegranate Salad", desc: "Antioxidants for rising energy." },
      { day: 7, title: "Avocado & Pumpkin Seed Toast", desc: "Healthy fats for hormone building." },
      { day: 8, title: "Grilled Salmon & Asparagus", desc: "Omega-3s and folate for cell health." },
      { day: 9, title: "Roasted Veggie Quinoa Bowl", desc: "Fiber to support estrogen metabolism." },
      { day: 10, title: "Chicken or Tofu Broccoli Stir-fry", desc: "Cruciferous veggies help process estrogen." },
      { day: 11, title: "Grated Carrot Salad with Apple Cider Vinegar", desc: "Supports liver detoxification." },
      { day: 12, title: "Plain Yogurt with Ground Flaxseeds", desc: "Phytoestrogens to balance hormones." },
      { day: 13, title: "Fresh Veggie Spring Rolls", desc: "Light, fresh, and hydrating." },
      { day: 14, title: "Green Energy Smoothie (Spinach, Pineapple, Ginger)", desc: "Vibrant energy for ovulation." },
      { day: 15, title: "Citrus Ceviche or Raw Veggie Salad", desc: "Cooling and refreshing for peak body temp." },
      { day: 16, title: "Raw Salmon, Edamame & Sesame Bowl", desc: "Light proteins and zinc." },
      { day: 17, title: "Roasted Sweet Potato Stuffed with Black Beans", desc: "Complex carbs to stabilize blood sugar." },
      { day: 18, title: "Turmeric Red Lentil Dahl", desc: "Liver support as estrogen drops." },
      { day: 19, title: "Buckwheat & Mushroom Skillet", desc: "B vitamins for sustained energy." },
      { day: 20, title: "Warm Beet & Walnut Salad", desc: "Supports blood flow and liver health." },
      { day: 21, title: "Whole Wheat Pasta with Kale Pesto", desc: "Sustained energy to combat fatigue." },
      { day: 22, title: "Homemade Hummus & Carrot Sticks", desc: "Stable snack to prevent sugar crashes." },
      { day: 23, title: "Butternut Squash & Pumpkin Seed Soup", desc: "Comforting and rich in zinc." },
      { day: 24, title: "Brown Rice, Turkey & Steamed Veggies", desc: "Tryptophan to boost serotonin." },
      { day: 25, title: "Baked Apple with Cinnamon & Walnuts", desc: "Satisfies sweet cravings naturally." },
      { day: 26, title: "Bean-Rich Vegetarian Chili", desc: "High fiber for satiety and digestion." },
      { day: 27, title: "Chamomile Tea & 70% Dark Chocolate", desc: "Magnesium for PMS relief." },
      { day: 28, title: "Root Vegetable Velouté", desc: "Grounding, warming, and easy to digest." }
    ]
  },
  fr: {
    title: "Plan de 28 jours (Œstrogènes)",
    desc: "Un guide quotidien pour nourrir votre corps selon les fluctuations d'œstrogènes tout au long de votre cycle.",
    btn: "Voir le plan de 28 jours",
    phases: {
      menstrual: "Phase Menstruelle (Jours 1-5) : Œstrogènes bas",
      follicular: "Phase Folliculaire (Jours 6-13) : Œstrogènes en hausse",
      ovulatory: "Phase Ovulatoire (Jours 14-16) : Pic d'œstrogènes",
      luteal: "Phase Lutéale (Jours 17-28) : Baisse et fluctuations"
    },
    days: [
      { day: 1, title: "Soupe réconfortante aux lentilles et épinards", desc: "Riche en fer pour compenser les pertes sanguines." },
      { day: 2, title: "Porridge chaud aux graines de chia et baies", desc: "Oméga-3 anti-inflammatoires pour les crampes." },
      { day: 3, title: "Bouillon de légumes aux champignons", desc: "Hydratant et riche en minéraux." },
      { day: 4, title: "Curry doux de pois chiches au lait de coco", desc: "Magnésium pour la relaxation musculaire." },
      { day: 5, title: "Smoothie cacao, banane et beurre d'amande", desc: "Énergie douce et soutien de l'humeur." },
      { day: 6, title: "Salade croquante de chou frisé et grenade", desc: "Antioxydants pour une énergie montante." },
      { day: 7, title: "Toast à l'avocat et graines de courge", desc: "Graisses saines pour la production hormonale." },
      { day: 8, title: "Saumon grillé et asperges", desc: "Oméga-3 et folates pour la santé cellulaire." },
      { day: 9, title: "Bol de quinoa aux légumes rôtis", desc: "Fibres pour soutenir le métabolisme des œstrogènes." },
      { day: 10, title: "Poulet ou tofu sauté aux brocolis", desc: "Les crucifères aident à éliminer l'excès d'œstrogènes." },
      { day: 11, title: "Salade de carottes râpées au vinaigre de cidre", desc: "Soutient la détoxification hépatique." },
      { day: 12, title: "Yaourt nature aux graines de lin moulues", desc: "Phytoœstrogènes pour équilibrer les hormones." },
      { day: 13, title: "Rouleaux de printemps aux légumes frais", desc: "Léger, frais et très hydratant." },
      { day: 14, title: "Smoothie vert (épinards, ananas, gingembre)", desc: "Énergie vibrante pour l'ovulation." },
      { day: 15, title: "Ceviche ou salade de crudités au citron", desc: "Rafraîchissant pour le pic de température corporelle." },
      { day: 16, title: "Bowl au saumon cru, edamame et sésame", desc: "Protéines légères et zinc." },
      { day: 17, title: "Patate douce rôtie farcie aux haricots noirs", desc: "Glucides complexes pour stabiliser la glycémie." },
      { day: 18, title: "Dahl de lentilles corail au curcuma", desc: "Soutien du foie lors de la baisse d'œstrogènes." },
      { day: 19, title: "Poêlée de champignons et sarrasin", desc: "Vitamines B pour une énergie durable." },
      { day: 20, title: "Salade tiède de betteraves et noix", desc: "Soutient la circulation sanguine et le foie." },
      { day: 21, title: "Pâtes complètes au pesto de chou frisé", desc: "Énergie durable pour combattre la fatigue." },
      { day: 22, title: "Houmous maison et bâtonnets de carottes", desc: "Collation stable pour éviter les fringales." },
      { day: 23, title: "Soupe à la courge butternut et graines de courge", desc: "Réconfortant et riche en zinc." },
      { day: 24, title: "Riz complet, dinde et légumes vapeur", desc: "Tryptophane pour stimuler la sérotonine." },
      { day: 25, title: "Pomme au four à la cannelle et noix", desc: "Satisfait les envies de sucre naturellement." },
      { day: 26, title: "Chili végétarien riche en haricots", desc: "Riche en fibres pour la satiété et la digestion." },
      { day: 27, title: "Tisane camomille et chocolat noir 70%", desc: "Magnésium pour soulager le SPM." },
      { day: 28, title: "Velouté de légumes racines", desc: "Ancrage, chaleur et facile à digérer." }
    ]
  },
  es: {
    title: "Plan de Recetas de 28 Días (Estrógeno)",
    desc: "Una guía diaria para nutrir tu cuerpo según las fluctuaciones de estrógeno a lo largo de tu ciclo.",
    btn: "Ver Plan de 28 Días",
    phases: {
      menstrual: "Fase Menstrual (Días 1-5): Estrógeno Bajo",
      follicular: "Fase Folicular (Días 6-13): Estrógeno en Aumento",
      ovulatory: "Fase Ovulatoria (Días 14-16): Pico de Estrógeno",
      luteal: "Fase Lútea (Días 17-28): Estrógeno Disminuye y Fluctúa"
    },
    days: [
      { day: 1, title: "Sopa reconfortante de lentejas y espinacas", desc: "Rica en hierro para reponer la pérdida de sangre." },
      { day: 2, title: "Gachas calientes de chía y bayas", desc: "Omega-3 antiinflamatorios para los calambres." },
      { day: 3, title: "Caldo de verduras con champiñones", desc: "Hidratante y lleno de oligoelementos." },
      { day: 4, title: "Curry suave de garbanzos con coco", desc: "Magnesio para la relajación muscular." },
      { day: 5, title: "Batido de cacao, plátano y almendras", desc: "Energía suave y apoyo al estado de ánimo." },
      { day: 6, title: "Ensalada crujiente de col rizada y granada", desc: "Antioxidantes para la energía en aumento." },
      { day: 7, title: "Tostada de aguacate y semillas de calabaza", desc: "Grasas saludables para la producción hormonal." },
      { day: 8, title: "Salmón a la parrilla y espárragos", desc: "Omega-3 y folato para la salud celular." },
      { day: 9, title: "Tazón de quinoa con verduras asadas", desc: "Fibra para apoyar el metabolismo del estrógeno." },
      { day: 10, title: "Salteado de pollo o tofu con brócoli", desc: "Las verduras crucíferas ayudan a procesar el estrógeno." },
      { day: 11, title: "Ensalada de zanahoria rallada con vinagre de sidra", desc: "Apoya la desintoxicación del hígado." },
      { day: 12, title: "Yogur natural con semillas de lino molidas", desc: "Fitoestrógenos para equilibrar las hormonas." },
      { day: 13, title: "Rollitos de primavera de verduras frescas", desc: "Ligeros, frescos e hidratantes." },
      { day: 14, title: "Batido verde (espinacas, piña, jengibre)", desc: "Energía vibrante para la ovulación." },
      { day: 15, title: "Ceviche de cítricos o ensalada de verduras crudas", desc: "Refrescante para el pico de temperatura corporal." },
      { day: 16, title: "Tazón de salmón crudo, edamame y sésamo", desc: "Proteínas ligeras y zinc." },
      { day: 17, title: "Batata asada rellena de frijoles negros", desc: "Carbohidratos complejos para estabilizar el azúcar." },
      { day: 18, title: "Dahl de lentejas rojas con cúrcuma", desc: "Apoyo hepático a medida que baja el estrógeno." },
      { day: 19, title: "Sartén de trigo sarraceno y champiñones", desc: "Vitaminas B para energía sostenida." },
      { day: 20, title: "Ensalada tibia de remolacha y nueces", desc: "Apoya el flujo sanguíneo y la salud del hígado." },
      { day: 21, title: "Pasta integral con pesto de col rizada", desc: "Energía sostenida para combatir la fatiga." },
      { day: 22, title: "Hummus casero y palitos de zanahoria", desc: "Snack estable para prevenir caídas de azúcar." },
      { day: 23, title: "Sopa de calabaza y semillas de calabaza", desc: "Reconfortante y rica en zinc." },
      { day: 24, title: "Arroz integral, pavo y verduras al vapor", desc: "Triptófano para aumentar la serotonina." },
      { day: 25, title: "Manzana al horno con canela y nueces", desc: "Satisface los antojos dulces de forma natural." },
      { day: 26, title: "Chili vegetariano rico en frijoles", desc: "Alto en fibra para la saciedad y digestión." },
      { day: 27, title: "Té de manzanilla y chocolate negro 70%", desc: "Magnesio para el alivio del SPM." },
      { day: 28, title: "Velouté de verduras de raíz", desc: "Enraizante, cálido y fácil de digerir." }
    ]
  },
  de: {
    title: "28-Tage-Östrogen-Rezeptplan",
    desc: "Ein täglicher Leitfaden zur Ernährung Ihres Körpers entsprechend den Östrogenschwankungen während Ihres Zyklus.",
    btn: "28-Tage-Plan ansehen",
    phases: {
      menstrual: "Menstruationsphase (Tage 1-5): Niedriges Östrogen",
      follicular: "Follikelphase (Tage 6-13): Steigendes Östrogen",
      ovulatory: "Eisprungphase (Tage 14-16): Östrogen-Höhepunkt",
      luteal: "Lutealphase (Tage 17-28): Östrogen sinkt & schwankt"
    },
    days: [
      { day: 1, title: "Tröstende Linsen-Spinat-Suppe", desc: "Reich an Eisen, um den Blutverlust auszugleichen." },
      { day: 2, title: "Warmer Chia-Beeren-Brei", desc: "Entzündungshemmende Omega-3-Fettsäuren bei Krämpfen." },
      { day: 3, title: "Pilz-Gemüse-Brühe", desc: "Feuchtigkeitsspendend und voller Spurenelemente." },
      { day: 4, title: "Mildes Kichererbsen-Kokos-Curry", desc: "Magnesium zur Muskelentspannung." },
      { day: 5, title: "Kakao-Bananen-Mandel-Smoothie", desc: "Sanfte Energie und Stimmungsunterstützung." },
      { day: 6, title: "Knuspriger Grünkohl-Granatapfel-Salat", desc: "Antioxidantien für steigende Energie." },
      { day: 7, title: "Avocado-Kürbiskern-Toast", desc: "Gesunde Fette für die Hormonbildung." },
      { day: 8, title: "Gegrillter Lachs & Spargel", desc: "Omega-3 und Folsäure für die Zellgesundheit." },
      { day: 9, title: "Geröstete Gemüse-Quinoa-Bowl", desc: "Ballaststoffe zur Unterstützung des Östrogenstoffwechsels." },
      { day: 10, title: "Hähnchen- oder Tofu-Brokkoli-Pfanne", desc: "Kreuzblütler helfen bei der Östrogenverarbeitung." },
      { day: 11, title: "Geriebener Karottensalat mit Apfelessig", desc: "Unterstützt die Leberentgiftung." },
      { day: 12, title: "Naturjoghurt mit gemahlenen Leinsamen", desc: "Phytoöstrogene zum Hormonausgleich." },
      { day: 13, title: "Frische Gemüse-Frühlingsrollen", desc: "Leicht, frisch und feuchtigkeitsspendend." },
      { day: 14, title: "Grüner Energie-Smoothie (Spinat, Ananas, Ingwer)", desc: "Lebendige Energie für den Eisprung." },
      { day: 15, title: "Zitrus-Ceviche oder Rohkostsalat", desc: "Kühlend und erfrischend für die höchste Körpertemperatur." },
      { day: 16, title: "Roher Lachs, Edamame & Sesam-Bowl", desc: "Leichte Proteine und Zink." },
      { day: 17, title: "Gebackene Süßkartoffel gefüllt mit schwarzen Bohnen", desc: "Komplexe Kohlenhydrate zur Blutzuckerstabilisierung." },
      { day: 18, title: "Kurkuma-Rote-Linsen-Dahl", desc: "Leberunterstützung, wenn das Östrogen sinkt." },
      { day: 19, title: "Buchweizen-Pilz-Pfanne", desc: "B-Vitamine für anhaltende Energie." },
      { day: 20, title: "Warmer Rote-Bete-Walnuss-Salat", desc: "Unterstützt die Durchblutung und Lebergesundheit." },
      { day: 21, title: "Vollkornnudeln mit Grünkohl-Pesto", desc: "Anhaltende Energie gegen Müdigkeit." },
      { day: 22, title: "Hausgemachter Hummus & Karottensticks", desc: "Stabiler Snack, um Zuckerabstürze zu vermeiden." },
      { day: 23, title: "Butternusskürbis-Kürbiskern-Suppe", desc: "Tröstend und reich an Zink." },
      { day: 24, title: "Naturreis, Pute & gedünstetes Gemüse", desc: "Tryptophan zur Steigerung von Serotonin." },
      { day: 25, title: "Bratapfel mit Zimt & Walnüssen", desc: "Befriedigt das Verlangen nach Süßem auf natürliche Weise." },
      { day: 26, title: "Bohnenreiches vegetarisches Chili", desc: "Ballaststoffreich für Sättigung und Verdauung." },
      { day: 27, title: "Kamillentee & 70% dunkle Schokolade", desc: "Magnesium zur PMS-Linderung." },
      { day: 28, title: "Wurzelgemüse-Velouté", desc: "Erdend, wärmend und leicht verdaulich." }
    ]
  },
  ja: {
    title: "28日間エストロゲンレシピプラン",
    desc: "周期を通じたエストロゲンの変動に合わせて体に栄養を与える毎日のガイド。",
    btn: "28日間プランを見る",
    phases: {
      menstrual: "月経期 (1-5日目): エストロゲン低下",
      follicular: "卵胞期 (6-13日目): エストロゲン上昇",
      ovulatory: "排卵期 (14-16日目): エストロゲンピーク",
      luteal: "黄体期 (17-28日目): エストロゲン低下と変動"
    },
    days: [
      { day: 1, title: "レンズ豆とほうれん草のスープ", desc: "失われた血液を補うための鉄分が豊富。" },
      { day: 2, title: "温かいチアとベリーのポリッジ", desc: "生理痛のための抗炎症オメガ3。" },
      { day: 3, title: "キノコと野菜のスープ", desc: "水分補給と微量ミネラルが豊富。" },
      { day: 4, title: "マイルドなひよこ豆のココナッツカレー", desc: "筋肉をリラックスさせるマグネシウム。" },
      { day: 5, title: "カカオ、バナナ、アーモンドのスムージー", desc: "穏やかなエネルギーと気分のサポート。" },
      { day: 6, title: "ケールとザクロのクランチサラダ", desc: "エネルギー上昇のための抗酸化物質。" },
      { day: 7, title: "アボカドとカボチャの種トースト", desc: "ホルモン生成のための健康的な脂肪。" },
      { day: 8, title: "グリルサーモンとアスパラガス", desc: "細胞の健康のためのオメガ3と葉酸。" },
      { day: 9, title: "ロースト野菜のキヌアボウル", desc: "エストロゲン代謝をサポートする食物繊維。" },
      { day: 10, title: "鶏肉または豆腐とブロッコリーの炒め物", desc: "アブラナ科の野菜がエストロゲン処理を助けます。" },
      { day: 11, title: "すりおろし人参とリンゴ酢のサラダ", desc: "肝臓の解毒をサポートします。" },
      { day: 12, title: "プレーンヨーグルトと粉砕フラックスシード", desc: "ホルモンバランスを整える植物性エストロゲン。" },
      { day: 13, title: "新鮮な野菜の生春巻き", desc: "軽くて新鮮、水分補給に最適。" },
      { day: 14, title: "グリーンエネルギースムージー", desc: "排卵のための活気に満ちたエネルギー。" },
      { day: 15, title: "シトラスセビチェまたは生野菜サラダ", desc: "体温のピーク時に涼しくさわやか。" },
      { day: 16, title: "生サーモン、枝豆、ごまのボウル", desc: "軽いタンパク質と亜鉛。" },
      { day: 17, title: "黒豆を詰めたローストサツマイモ", desc: "血糖値を安定させる複合炭水化物。" },
      { day: 18, title: "ターメリックレッドレンズ豆のダール", desc: "エストロゲン低下時の肝臓サポート。" },
      { day: 19, title: "そばの実とキノコのスキレット", desc: "持続的なエネルギーのためのビタミンB群。" },
      { day: 20, title: "温かいビーツとクルミのサラダ", desc: "血流と肝臓の健康をサポートします。" },
      { day: 21, title: "全粒粉パスタとケールペスト", desc: "疲労と戦うための持続的なエネルギー。" },
      { day: 22, title: "自家製フムスとキャロットスティック", desc: "血糖値の急降下を防ぐ安定したおやつ。" },
      { day: 23, title: "バターナッツスクワッシュとカボチャの種のスープ", desc: "心地よく、亜鉛が豊富。" },
      { day: 24, title: "玄米、七面鳥、蒸し野菜", desc: "セロトニンを増やすトリプトファン。" },
      { day: 25, title: "焼きリンゴのシナモンとクルミ添え", desc: "甘いものへの欲求を自然に満たします。" },
      { day: 26, title: "豆たっぷりのベジタリアンチリ", desc: "満腹感と消化のための高食物繊維。" },
      { day: 27, title: "カモミールティーと70%ダークチョコレート", desc: "PMS緩和のためのマグネシウム。" },
      { day: 28, title: "根菜のヴルーテ", desc: "地に足がつき、温かく、消化しやすい。" }
    ]
  },
  pt: {
    title: "Plano de Receitas de 28 Dias (Estrogênio)",
    desc: "Um guia diário para nutrir seu corpo de acordo com as flutuações de estrogênio ao longo do seu ciclo.",
    btn: "Ver Plano de 28 Dias",
    phases: {
      menstrual: "Fase Menstrual (Dias 1-5): Estrogênio Baixo",
      follicular: "Fase Folicular (Dias 6-13): Estrogênio em Aumento",
      ovulatory: "Fase Ovulatória (Dias 14-16): Pico de Estrogênio",
      luteal: "Fase Lútea (Dias 17-28): Estrogênio Cai e Flutua"
    },
    days: [
      { day: 1, title: "Sopa reconfortante de lentilha e espinafre", desc: "Rica em ferro para repor a perda de sangue." },
      { day: 2, title: "Mingau quente de chia e frutas vermelhas", desc: "Ômega-3 anti-inflamatórios para cólicas." },
      { day: 3, title: "Caldo de legumes com cogumelos", desc: "Hidratante e repleto de minerais." },
      { day: 4, title: "Curry suave de grão de bico com coco", desc: "Magnésio para relaxamento muscular." },
      { day: 5, title: "Vitamina de cacau, banana e amêndoa", desc: "Energia suave e apoio ao humor." },
      { day: 6, title: "Salada crocante de couve e romã", desc: "Antioxidantes para energia crescente." },
      { day: 7, title: "Torrada de abacate e semente de abóbora", desc: "Gorduras saudáveis para produção hormonal." },
      { day: 8, title: "Salmão grelhado e aspargos", desc: "Ômega-3 e folato para saúde celular." },
      { day: 9, title: "Tigela de quinoa com legumes assados", desc: "Fibras para apoiar o metabolismo do estrogênio." },
      { day: 10, title: "Refogado de frango ou tofu com brócolis", desc: "Vegetais crucíferos ajudam a processar o estrogênio." },
      { day: 11, title: "Salada de cenoura ralada com vinagre de maçã", desc: "Apoia a desintoxicação do fígado." },
      { day: 12, title: "Iogurte natural com sementes de linhaça moídas", desc: "Fitoestrogênios para equilibrar os hormônios." },
      { day: 13, title: "Rolinhos primavera de vegetais frescos", desc: "Leve, fresco e hidratante." },
      { day: 14, title: "Vitamina verde (espinafre, abacaxi, gengibre)", desc: "Energia vibrante para a ovulação." },
      { day: 15, title: "Ceviche cítrico ou salada de vegetais crus", desc: "Refrescante para o pico de temperatura corporal." },
      { day: 16, title: "Tigela de salmão cru, edamame e gergelim", desc: "Proteínas leves e zinco." },
      { day: 17, title: "Batata doce assada recheada com feijão preto", desc: "Carboidratos complexos para estabilizar o açúcar." },
      { day: 18, title: "Dahl de lentilha vermelha com cúrcuma", desc: "Apoio hepático à medida que o estrogênio cai." },
      { day: 19, title: "Frigideira de trigo sarraceno e cogumelos", desc: "Vitaminas B para energia sustentada." },
      { day: 20, title: "Salada morna de beterraba e nozes", desc: "Apoia o fluxo sanguíneo e a saúde do fígado." },
      { day: 21, title: "Massa integral com pesto de couve", desc: "Energia sustentada para combater a fadiga." },
      { day: 22, title: "Homus caseiro e palitos de cenoura", desc: "Lanche estável para evitar quedas de açúcar." },
      { day: 23, title: "Sopa de abóbora e sementes de abóbora", desc: "Reconfortante e rica em zinco." },
      { day: 24, title: "Arroz integral, peru e legumes no vapor", desc: "Triptofano para aumentar a serotonina." },
      { day: 25, title: "Maçã assada com canela e nozes", desc: "Satisfaz os desejos por doces naturalmente." },
      { day: 26, title: "Chili vegetariano rico em feijão", desc: "Rico em fibras para saciedade e digestão." },
      { day: 27, title: "Chá de camomila e chocolate amargo 70%", desc: "Magnésio para alívio da TPM." },
      { day: 28, title: "Velouté de raízes", desc: "Aterrador, quente e fácil de digerir." }
    ]
  },
  it: {
    title: "Piano di Ricette di 28 Giorni (Estrogeni)",
    desc: "Una guida quotidiana per nutrire il tuo corpo in base alle fluttuazioni degli estrogeni durante il ciclo.",
    btn: "Vedi Piano di 28 Giorni",
    phases: {
      menstrual: "Fase Mestruale (Giorni 1-5): Estrogeni Bassi",
      follicular: "Fase Follicolare (Giorni 6-13): Estrogeni in Aumento",
      ovulatory: "Fase Ovulatoria (Giorni 14-16): Picco di Estrogeni",
      luteal: "Fase Luteale (Giorni 17-28): Estrogeni in Calo e Fluttuanti"
    },
    days: [
      { day: 1, title: "Zuppa confortante di lenticchie e spinaci", desc: "Ricca di ferro per reintegrare la perdita di sangue." },
      { day: 2, title: "Porridge caldo di chia e frutti di bosco", desc: "Omega-3 antinfiammatori per i crampi." },
      { day: 3, title: "Brodo di verdure e funghi", desc: "Idratante e ricco di oligoelementi." },
      { day: 4, title: "Curry delicato di ceci al cocco", desc: "Magnesio per il rilassamento muscolare." },
      { day: 5, title: "Frullato di cacao, banana e mandorle", desc: "Energia delicata e supporto per l'umore." },
      { day: 6, title: "Insalata croccante di cavolo nero e melograno", desc: "Antiossidanti per l'energia in aumento." },
      { day: 7, title: "Toast con avocado e semi di zucca", desc: "Grassi sani per la produzione ormonale." },
      { day: 8, title: "Salmone grigliato e asparagi", desc: "Omega-3 e folati per la salute cellulare." },
      { day: 9, title: "Ciotola di quinoa con verdure arrostite", desc: "Fibre per supportare il metabolismo degli estrogeni." },
      { day: 10, title: "Pollo o tofu saltato con broccoli", desc: "Le verdure crocifere aiutano a elaborare gli estrogeni." },
      { day: 11, title: "Insalata di carote grattugiate con aceto di mele", desc: "Supporta la disintossicazione del fegato." },
      { day: 12, title: "Yogurt bianco con semi di lino macinati", desc: "Fitoestrogeni per bilanciare gli ormoni." },
      { day: 13, title: "Involtini primavera di verdure fresche", desc: "Leggeri, freschi e idratanti." },
      { day: 14, title: "Frullato verde (spinaci, ananas, zenzero)", desc: "Energia vibrante per l'ovulazione." },
      { day: 15, title: "Ceviche di agrumi o insalata di verdure crude", desc: "Rinfrescante per il picco di temperatura corporea." },
      { day: 16, title: "Ciotola di salmone crudo, edamame e sesamo", desc: "Proteine leggere e zinco." },
      { day: 17, title: "Patata dolce arrostita ripiena di fagioli neri", desc: "Carboidrati complessi per stabilizzare la glicemia." },
      { day: 18, title: "Dahl di lenticchie rosse alla curcuma", desc: "Supporto epatico quando gli estrogeni calano." },
      { day: 19, title: "Padellata di grano saraceno e funghi", desc: "Vitamine B per energia prolungata." },
      { day: 20, title: "Insalata tiepida di barbabietole e noci", desc: "Supporta il flusso sanguigno e la salute del fegato." },
      { day: 21, title: "Pasta integrale con pesto di cavolo nero", desc: "Energia prolungata per combattere la fatica." },
      { day: 22, title: "Hummus fatto in casa e bastoncini di carota", desc: "Spuntino stabile per prevenire cali di zuccheri." },
      { day: 23, title: "Zuppa di zucca e semi di zucca", desc: "Confortante e ricca di zinco." },
      { day: 24, title: "Riso integrale, tacchino e verdure al vapore", desc: "Triptofano per aumentare la serotonina." },
      { day: 25, title: "Mela al forno con cannella e noci", desc: "Soddisfa la voglia di dolce in modo naturale." },
      { day: 26, title: "Chili vegetariano ricco di fagioli", desc: "Ricco di fibre per sazietà e digestione." },
      { day: 27, title: "Camomilla e cioccolato fondente 70%", desc: "Magnesio per il sollievo dalla sindrome premestruale." },
      { day: 28, title: "Vellutata di ortaggi a radice", desc: "Radicante, calda e facile da digerire." }
    ]
  }
};
